src/QuickRepricer/Controllers/Web/AppController.cs
using Microsoft.AspNetCore.Mvc;
using QuickRepricer.Core.ViewModels;
using QuickRepricer.Core.Models;
using Microsoft.AspNetCore.Identity;

namespace QuickRepricer.Controllers.Web
{
    [RequireHttps]
    public class AppController : Controller
    {
        private SignInManager<ApplicationUser> _signInManager;

        public AppController(SignInManager<ApplicationUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            if (_signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                return View();
            }
        }

        public IActionResult About()
        {
           

            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Faq()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Terms()
        {
            return View();

        }


        public IActionResult RefundPolicy()
        {
            return View();
        }

        public IActionResult Contact()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel vm)
        {
            if (ModelState.IsValid)
            {
                //_mailservice.SendMail(_config["MailSettings:ToSupportAddress"], vm.Email, "From Repricerbot", vm.Message);

                ModelState.Clear();

                ViewData["Message"] = "Message sent";
                return RedirectToAction("Index");
            }

            return BadRequest(ModelState);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/QuickRepricer/Controllers/Web/SubscriptionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Stripe;
using System.Threading.Tasks;
using QuickRepricer.Core.Services.Subscription;
using QuickRepricer.Core.Services.Subscription.Plans;
using QuickRepricer.Core.ViewModels.SubscriptionViewModels;

namespace QuickRepricer.Controllers.Web
{
    [RequireHttps]
    public class SubscriptionController : Controller
    {
        private IPlanService _planService;
        private ISubscriptionService _subscriptionService;
        private IConfigurationRoot _config;

        public SubscriptionController(IPlanService planService, 
            ISubscriptionService subscriptionService,
            IConfigurationRoot config)
        {

            _planService = planService;
            _subscriptionService = subscriptionService;
            _config = config;
        }
        
        public async Task<IActionResult> Index()
        {
            var plans = await _planService.ListAsync();
            var viewModel = new SubscriptionIndexViewModel()
            {
                Plans = plans
            };
            
            return View(viewModel);
        }


        public async Task<IActionResult> Billing(int planId)
        {
            string stripePublishableKey = _config["PaymentSettings:Stripe:PublicKey"];

            var plan = await _planService.FindAsync(planId);

            var viewModel = new BillingViewModel() {
                Plan = plan,
                StripePublishableKey = stripePublishableKey
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Billing(BillingViewModel billingViewModel)
        {
            billingViewModel.Plan = await _planService.FindAsync(billingViewModel.Plan.Id);

            try
            {
                await _subscriptionService.CreateOrUpdateAsync(User.Identity.Name, billingViewModel.Plan, billingViewModel.StripeToken);
            }
            catch (StripeException stripeException)
            {
                ModelState.AddModelError(string.Empty, stripeException.Message);
                return View(billingViewModel);
            }

            return RedirectToAction("Index", "Dashboard");
        }

    }
}

src/QuickRepricer/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>QuickRepricer - @ViewData["Title"]</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @*<link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700" rel="stylesheet">*@
    <environment names="Development">
        <link href="~/lib/materialize/dist/css/materialize.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"
              asp-fallback-href="~/lib/materialize/dist/css/materialize.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    <div class="navbar-fixed">
        @if (SignInManager.IsSignedIn(User))
        {
            <ul id="loggedin-dropdown" class="dropdown-content">
                <li>
                    <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">
                        <i class="material-icons left">settings</i>Settings
                    </a>
                </li>
                <li class="divider"></li>
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <li>
                        <a href="javascript:document.getElementById('logoutForm').submit()" title="Log off">
                            <i class="material-icons left">input</i>Log off
                        </a>
                    </li>
                }
            </ul>

            <ul id="notifications-dropdown" class="dropdown-content dropdown-notification">
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
                <li>
                    <a href="#!">
                        <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                    </a>
                </li>
            </ul>

            <div id="notification-modal" class="modal bottom-sheet">
                <div class="modal-content">
                    <ul>
                        <li>
                            <div class="row">
                                <a href="#!">
                                    <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                                </a>
                            </div>
                        </li>
                        <li>
                            <div class="row">
                                <a href="#!">
                                    <i class="material-icons left small">priority_high</i> A new order has been placed! <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <a href="#!" class="modal-action modal-close waves-effect waves-green btn">Close</a>
                </div>
            </div>
        }
        <nav class="light-blue lighten-1" role="navigation">
            <div class="nav-wrapper navmargin">

                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="brand-logo" asp-area="" asp-controller="Dashboard" asp-action="Index">Quick Repricer</a>
                }
                else
                {
                    <a class="brand-logo" asp-area="" asp-controller="App" asp-action="Index">Quick Repricer</a>
                }

                <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons white-text">menu</i></a>

                <ul class="right hide-on-med-and-down">
                    @await Html.PartialAsync("_NavPartial")
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li>
                            <a class="dropdown-button" href="#!" data-activates="notifications-dropdown" data-beloworigin="true">
                                <i class="material-icons left">notifications</i>
                                <small class="notification-badge"><block>5</block></small>
                            </a>
                        </li>

                        <li>
                            <a class="dropdown-button" href="#!" data-activates="loggedin-dropdown" data-beloworigin="true">
                                @UserManager.GetUserName(User) <i class="material-icons right">arrow_drop_down</i>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-area="" asp-controller="Account" asp-action="Login" class="btn green white-text">Login</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Subscription" asp-action="Index" class="btn orange white-text">Try for Free</a>
                        </li>
                    }
                </ul>
                <ul id="slide-out" class="side-nav light-blue lighten-5">
                    <li><a class="waves-effect" asp-area="" asp-controller="App" asp-action="Index">Home</a></li>
                    @await Html.PartialAsync("_NavPartial")

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li>
                            <a class="waves-effect waves-light modal-trigger" href="#notification-modal">
                                <i class="material-icons left">notifications</i>
                                <small class="notification-badge"><block>5</block></small>
                            </a>
                        </li>
                    }

                    @await Html.PartialAsync("_MobLoginPartial")
                </ul>
            </div>
        </nav>
    </div>

    <div id="fb-root"></div>

    <main>
        @RenderBody()

    </main>
    
    <footer class="page-footer light-blue lighten-1">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Quick Repricer</h5>
                    <p class="grey-text text-lighten-4">Changing the face of Retail.</p>
                    <p class="grey-text text-lighten-4">&copy; 2016 - Quick Repricer Ltd. All rights reserved.</p>
                </div>
                <div class="col l6 s12">
                    <h5 class="white-text">Quick Links</h5>
                    <ul>
                        <li><a class="white-text" asp-area="" asp-controller="App" asp-action="About">About Us</a></li>
                        <li><a class="white-text" asp-controller="App" asp-action="Blog">Blog</a></li>
                        <li><a class="white-text" asp-controller="App" asp-action="Faq">Product Faq</a></li>
                        <li><a class="white-text" asp-controller="App" asp-action="Contact">Contact Us</a></li>
                        <li><a class="white-text" asp-controller="App" asp-action="Privacy">Privacy</a></li>
                        <li><a class="white-text" asp-controller="App" asp-action="Terms">Terms of Service</a></li>
                        <li><a class="white-text" asp-controller="App" asp-action="RefundPolicy">Refund Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="brown-text text-lighten-3" href="https://wwww.jbsoft.com">JB Soft Ltd.</a>
            </div>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/materialize/dist/js/materialize.js"></script>
        <script src="~/lib/momentjs/moment.js"></script>
        <script src="~/lib/js-cookie/src/js.cookie.js"></script>
        <script src="~/js/app/controllers/subscriptionController.js"></script>
        <script src="~/js/app/controllers/utilityController.js"></script>
        <script src="~/js/app/app.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"
                    asp-fallback-src="~/lib/materialize/dist/js/materialize.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>*@
        <script src="~/lib/materialize/dist/js/materialize.min.js"
                asp-fallback-src="~/lib/materialize/dist/js/materialize.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"
                asp-fallback-src="~/lib/momentjs/min/moment.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.min.js"
                asp-fallback-src="~/lib/js-cookie/src/js.cookie.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/js/app/controllers/subscriptionController.min.js"></script>
        <script src="~/js/app/controllers/utilityController.min.js"></script>
        <script src="~/js/app/app.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>

src/QuickRepricer/Views/Shared/_MobLoginPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (SignInManager.IsSignedIn(User))
{
    <li>
        <ul class="collapsible collapsible-accordion">
            <li>
                <a class="collapsible-header waves-effect waves-teal">@UserManager.GetUserName(User)<i class="material-icons right">arrow_drop_down</i></a>
                <div class="collapsible-body" style="background-color:transparent">
                    <ul>
                        <li>
                            <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">
                                Settings
                            </a>
                        </li>
                        <li class="divider"></li>
                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <li>                              
                                <a href="javascript:document.getElementById('logoutForm').submit()" title="Log off">
                                    Log off
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </li>
        </ul>
    </li>
}
else
{
    <li><a asp-area="" asp-controller="Account" asp-action="Login" class="btn green white-text">Login</a></li>
    <li><a asp-area="" asp-controller="Subscription" asp-action="Index" class="btn orange white-text">Try for Free</a></li>
}

src/QuickRepricer/Views/Shared/_NavPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager
<li><a class="waves-effect" asp-area="" asp-controller="App" asp-action="About">About</a></li>
<li><a class="waves-effect" asp-area="" asp-controller="App" asp-action="Blog">Blog</a></li>
<li><a class="waves-effect" asp-area="" asp-controller="App" asp-action="Contact">Contact</a></li>

@if (SignInManager.IsSignedIn(User))
{
    <li>
        <a asp-area="" asp-controller="Subscription" asp-action="Index">
            <div class="chip orange white-text">
                <span class="white-text">Upgrade</span>
            </div>
        </a>
    </li>
    <li>
        <a class="waves-effect" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </li>
}
else
{
    <li>
        <a asp-area="" asp-controller="Subscription" asp-action="Index">Pricing</a>
    </li>
}